name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a99c9e54feab125756018a1b0fde12536eab02647a249b6fffa2ec1deb38b9e2"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
