name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dc5973cd1062012e4c0f19046b4c1a7f6110ecc379ca8a3a979dee5ce67cdc5"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
