name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b83304740f4bd96eb748f3906105f05e7e38b4d0321a4239aa3185b484be9fe5"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
