name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddacb8ca9fa54f170c987a0c170c6a6e59d92c5705464fbb83ad14aba2db0da8"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
