name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e70269e69e91680b9e224004f452624e263ceccfb12affc0a95a0a83ee9bf51"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
