name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3333ab07c548b51e927e1392dde2fa1c5097e4033def4713156321a03c03f608"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
