name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bd97896999d334b5301415ea1e4a868e5bae5bb0536d6403c95b095b414450e"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
