name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98604fa7a9662ac5d913dc4c74b5feb23535b58a8359a70d32ebef45163f10d9"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
