name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4af4a4a58bf70e01424afed3d04f9b6f48e9440b4f90897b552ba1994c397d20"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
