name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd9f20b462b7a02c019b21728c563d0e65563f7518c2f28ac6bec31f77deb57d"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
