name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f22030ad8f230ec8c957f1a6ec9eb2ca3acda0d6b0903425300406a765db384"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
