name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8e5b1aac9717501f180c5bed6c0465565d06037c75ac40465102a0f6448ae86"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
