name = "caneva20's Create 1.19 [Forge]"
author = "caneva20"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bbbd08ccd721174b5b4ea908b6343560b6c40f2388fd491aaf8a79c57b010fd"

[versions]
forge = "40.2.9"
minecraft = "1.18.2"
